version: '3.8'

services:
  app:
    build:
      context: .
      args:
        - NOTION_SECRET=${NOTION_SECRET}
        - NOTION_DATABASE_ID=${NOTION_DATABASE_ID}
    ports:
      - "3000:3000"
    environment:
      - NOTION_SECRET=${NOTION_SECRET}
      - NOTION_DATABASE_ID=${NOTION_DATABASE_ID}